services:
  - type: static
    name: react-assignment-${RENDER_GIT_REPO_SLUG}
    env: static
    buildCommand: npm install && npm run build
    publishPath: dist
    autoDeploy: true # This is the magic line
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    # Optional: Ensures the site is "healthy" before showing it to you
    healthCheckPath: /
